services:
  - type: web
    name: hackrx-document-qa
    env: python
    plan: starter
    buildCommand: |
      apt-get update && apt-get install -y \
        build-essential \
        gcc \
        g++ \
        python3-dev \
        libffi-dev \
        libssl-dev \
        && pip install --upgrade pip setuptools wheel \
        && pip install --no-cache-dir -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
      - key: GOOGLE_API_KEY
        fromSecret: GOOGLE_API_KEY
      - key: LLAMA_CLOUD_API_KEY  
        fromSecret: LLAMA_CLOUD_API_KEY
      - key: GROQ_API_KEY
        fromSecret: GROQ_API_KEY
      - key: PINECONE_API_KEY
        fromSecret: PINECONE_API_KEY
      - key: PINECONE_INDEX
        value: existing-index
      - key: PINECONE_NAMESPACE
        value: rag-hybrid
      - key: PINECONE_ENVIRONMENT
        value: us-east-1
